name: Sync DAGs

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if:  ${{ github.event.workflow_run.conclusion  == 'success' }}
    steps:
        - name: Deploy on main 
          run: |
            echo "Deploying in main :)"
            echo "head_ref: ${{ github.head_ref }} "
            echo "base_ref: ${{ github.base_ref }} "
            echo "ref_name: ${{ github.ref_name }}"
