name: Sync DAGs

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'development'}}
    steps:
        - name: Deploy on main 
          run: |
            echo "Deploying in main :)"
