name: Sync DAGs

on:
  workflow_run:
    workflows:
      - 'Test DAGs'
    types:
      - completed
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion  == 'success' }} && ${{ github.event.pull_request.base.ref == 'main' }}
    steps:
        - name: Deploy on main 
          run: |
            echo "Deploying in main"
            echo "${{ github.event.workflow_run.conclusion  == 'success' }}"
            echo "${{ github.event.pull_request.base.ref == 'main' }}"
            echo "${{ github.event.pull_request.base.ref }}"
            echo "Deployed :D"
          