name: Sync DAGs

on:
  workflow_run:
    workflows:
      - 'Test DAGs'
    types:
      - completed
  pull_request:
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if:  ${{ github.event.workflow_run.conclusion  == 'success' && github.ref_name == 'main' }}
    steps:
        - name: Deploy on main 
          run: |
            echo "Deploying in main :D"
