# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test Dags

on:
  pull_request:
    branches: [ "main","development" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.6"
    - name: Check branch name
      run: |
        echo "${{ github.head_ref }}"
        echo "${{ github.ref_name }}"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements.txt
        pip check
    - name: Test DAGs with Flake8
      run: |
        pip install flake8==4.0.1
        flake8 --ignore E501 dags --benchmark -v
    # - name: Confirm Black code compliance fo DAGs
    #   run: |
    #     pip install pytest-black==0.3.12
    #     pytest dags --black -v
    - name: Test DAGs with Pytest
      run: |
        pip install pytest==7.4.2
        pushd test || exit
        python3 -m pytest test_dags.py -v || exit
        popd || exit
